include:
  - project: "devops/ci-cd-templates"
    file:
      - "templates.yml"

stages:
  - ci

ci:
  stage: ci
  image: ${REGISTRY_URL}/fleet/fleet/rust-base:2
  tags:
    - shared-amd64-high
  before_script:
    - apt-get update -qq
    - apt-get install cmake libxcb-xfixes0-dev libxcb-shape0-dev -qqy
  script:
    - cargo build
    - cargo nextest run --no-fail-fast --no-tests pass
    - cargo clippy --no-deps -- -D warnings
    - cargo fmt --check
